FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
	&& apt-get install -y \
		apt-utils wget sudo build-essential \
		g++-multilib \
		flex bison libtool-bin texinfo git \
		python3 python3-pip \
	&& rm -rf /var/lib/apt/lists/*

RUN pip3 install pylint pytest gcovr

RUN useradd -rm -d /home/user -s /bin/bash -u $UID user
RUN echo "user ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/user
USER user
RUN id

WORKDIR /home/user
