FROM ubuntu:18.04 AS base_img

# label history
#   u18.04v001 - base image used to build other images

LABEL maintainer="neocliff@mac.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y \
        apt-utils sudo wget libssl-dev \
        build-essential \
        g++-multilib automake autoconf \
        flex bison libtool-bin texinfo \
        git xz-utils libpcre3-dev \
		python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*
